# Generated by Django 6.0.7 on 2026-08-17 18:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('meal_plan', models.CharField(choices=[('breakfast', 'Breakfast'), ('two_meals', '2 meals'), ('three_meals', '3 meals'), ('all_inclusive', 'All Inclusive'), ('included', 'Included')], max_length=20)),
                ('transfer_type', models.CharField(choices=[('group', 'Group'), ('private', 'Private')], max_length=20)),
                ('hotel_name', models.CharField(max_length=150)),
                ('hotel_type', models.CharField(max_length=50)),
                ('ticket_included', models.BooleanField(default=False)),
                ('baggage_included', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children_under_2', models.PositiveIntegerField(default=0)),
                ('children_2_12', models.PositiveIntegerField(default=0)),
                ('children_12_plus', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('AMD', 'AMD'), ('USD', 'USD'), ('EUR', 'EUR')], default='AMD', max_length=3)),
                ('airline_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/')),
                ('is_main', models.BooleanField(default=False)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour')),
            ],
        ),
    ]
