# Generated by Django 6.0.7 on 2026-08-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Վերնագիր')),
                ('description', models.TextField(verbose_name='Նկարագրություն')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Թարմացման ամսաթիվ')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
