# Generated by Django 6.0.7 on 2026-08-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='news.tag'),
        ),
        migrations.AddField(
            model_name='articledetail',
            name='tags',
            field=models.ManyToManyField(blank=True, to='news.tag'),
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(blank=True, to='news.tag'),
        ),
        migrations.AddField(
            model_name='categorydetail',
            name='tags',
            field=models.ManyToManyField(blank=True, to='news.tag'),
        ),
    ]
